const snapshots={current:{score:68,previous:61},previous:{score:61,previous:58}};
const areaScores=[{name:"DLP policies",current:58,previous:42},{name:"Tenant settings",current:82,previous:79},{name:"Managed environments",current:71,previous:63},{name:"Tenant isolation",current:36,previous:36},{name:"Sharing & ownership",current:64,previous:58},{name:"AI governance",current:75,previous:69}];
const environments=[
{id:"default",name:"Northstar Default",type:"Default",region:"Europe",managed:false,dlp:false,apps:86,flows:142,orphaned:7,risk:"high",securityGroup:"None",findings:["PPG-DLP-002","PPG-SHR-001","PPG-ENV-001"]},
{id:"prod-sales",name:"Sales Production",type:"Production",region:"Europe",managed:true,dlp:true,apps:24,flows:51,orphaned:1,risk:"low",securityGroup:"PP-Sales-Users",findings:["PPG-SHR-002"]},
{id:"prod-ops",name:"Operations Production",type:"Production",region:"Europe",managed:false,dlp:true,apps:37,flows:74,orphaned:2,risk:"medium",securityGroup:"PP-Ops-Users",findings:["PPG-ENV-002","PPG-SHR-002"]},
{id:"dev-core",name:"Core Solutions DEV",type:"Developer",region:"Europe",managed:true,dlp:true,apps:19,flows:33,orphaned:0,risk:"low",securityGroup:"PP-Core-Makers",findings:[]},
{id:"test-core",name:"Core Solutions TEST",type:"Sandbox",region:"Europe",managed:true,dlp:true,apps:16,flows:28,orphaned:0,risk:"low",securityGroup:"PP-Core-Testers",findings:[]},
{id:"hr",name:"People Services",type:"Production",region:"Europe",managed:true,dlp:true,apps:11,flows:21,orphaned:0,risk:"low",securityGroup:"PP-HR-Users",findings:[]},
{id:"trial",name:"Innovation Trial",type:"Trial",region:"United States",managed:false,dlp:false,apps:9,flows:13,orphaned:2,risk:"high",securityGroup:"None",findings:["PPG-DLP-002","PPG-ENV-004","PPG-ISO-001"]},
{id:"coe",name:"Center of Excellence",type:"Production",region:"Europe",managed:true,dlp:true,apps:31,flows:58,orphaned:0,risk:"low",securityGroup:"PP-CoE-Admins",findings:[]}
];
const findings=[
{id:"PPG-SHR-001",title:"Apps are shared tenant-wide in the default environment",area:"Sharing & ownership",severity:"Critical",status:"Fail",scope:"Northstar Default",evidence:"4 apps use the Everyone principal; 2 contain Dataverse connections.",impact:"Broad sharing in the default environment can expose business data and bypass intended access boundaries.",recommendation:"Review the four apps, replace Everyone sharing with security groups, and confirm owners before the next snapshot.",effort:"Medium",current:true,previous:true},
{id:"PPG-DLP-002",title:"Two environments are not covered by a DLP policy",area:"DLP policies",severity:"High",status:"Fail",scope:"Northstar Default, Innovation Trial",evidence:"6 of 8 environments are included in at least one tenant or environment policy.",impact:"Makers can combine business data with ungoverned connectors in uncovered environments.",recommendation:"Extend the tenant baseline policy to all environments and apply a stricter policy to the default environment.",effort:"Low",current:true,previous:true},
{id:"PPG-ISO-001",title:"Outbound tenant isolation is not enabled",area:"Tenant isolation",severity:"High",status:"Fail",scope:"Tenant",evidence:"Inbound restriction: enabled. Outbound restriction: disabled. Allowlist: empty.",impact:"Connections may exchange data with resources in external Power Platform tenants.",recommendation:"Define approved external tenants, test dependent integrations, then enable outbound isolation with an explicit allowlist.",effort:"Medium",current:true,previous:true},
{id:"PPG-ENV-002",title:"Production environment is not managed",area:"Managed environments",severity:"High",status:"Fail",scope:"Operations Production",evidence:"Environment type is Production; governanceConfiguration.protectionLevel is Standard.",impact:"Sharing limits, usage insights, and managed environment controls are unavailable for a production workload.",recommendation:"Validate premium licensing and enable Managed Environments for Operations Production.",effort:"Low",current:true,previous:true},
{id:"PPG-SHR-002",title:"Orphaned apps and flows require ownership",area:"Sharing & ownership",severity:"High",status:"Partial",scope:"3 environments",evidence:"12 resources have an owner whose directory account is disabled or not found.",impact:"Business-critical automation may have no accountable owner for maintenance or incident response.",recommendation:"Assign active business and technical owners to the 12 resources, starting with production flows.",effort:"Medium",current:true,previous:true},
{id:"PPG-ENV-004",title:"Trial environment exceeds 30-day policy",area:"Managed environments",severity:"Medium",status:"Fail",scope:"Innovation Trial",evidence:"Environment age is 47 days and no approved exception is recorded.",impact:"Long-lived trials increase unmanaged inventory and may retain experimental connections or data.",recommendation:"Confirm the business owner, then convert, reset, or remove the trial environment.",effort:"Low",current:true,previous:false},
{id:"PPG-TEN-006",title:"Production environment creation is restricted",area:"Tenant settings",severity:"Low",status:"Pass",scope:"Tenant",evidence:"disableEnvironmentCreationByNonAdminUsers is true.",impact:"Environment creation follows the approved administration path.",recommendation:"No action required. Continue monitoring for configuration drift.",effort:"None",current:true,previous:true},
{id:"PPG-AI-002",title:"Cross-region generative AI data movement is blocked",area:"AI governance",severity:"Low",status:"Pass",scope:"Tenant",evidence:"Generative AI data movement outside the configured geography is disabled.",impact:"AI processing remains aligned with the tenant geography policy.",recommendation:"No action required. Revalidate when new Copilot Studio controls become available.",effort:"None",current:true,previous:true}
];
const coverage=[["Tenant settings","Full","Known settings parsed; raw snapshot retained"],["Environments","Full","8 environments and governance properties"],["DLP policies","Full","3 policies and connector classifications"],["Tenant isolation","Full","Inbound, outbound and allowlist state"],["Apps","Full","233 apps with ownership metadata"],["Flows","Partial","420 flows; sharing details unavailable in app-only mode"],["Directory owners","Full","Owner account state resolved"],["Environment groups","Full","2 groups and memberships"]];
let activeSnapshot="current",selectedEnvironment="default",selectedFinding="PPG-SHR-001";
const viewCopy={overview:["Tenant overview","Prioritize governance gaps from the latest Power Platform snapshot."],environments:["Environment explorer","Compare management, DLP coverage, ownership, and risk across the estate."],findings:["Governance findings","Filter evidence-backed controls and choose the next remediation action."]};
const $=selector=>document.querySelector(selector); const $$=selector=>document.querySelectorAll(selector);
const snapshotFindings=()=>findings.filter(item=>item[activeSnapshot]);
const severityRank=severity=>({Critical:4,High:3,Medium:2,Low:1}[severity]||0);
function activate(element,callback){element.addEventListener("click",callback);element.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();callback();}})}
function openView(name){$$('.view').forEach(view=>view.classList.toggle('active',view.id===`${name}View`));$$('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===name));$('#viewTitle').textContent=viewCopy[name][0];$('#viewDescription').textContent=viewCopy[name][1];if(name==='environments')renderEnvironments();if(name==='findings')renderFindings();}
function renderOverview(){const snap=snapshots[activeSnapshot],open=snapshotFindings().filter(item=>item.status!=="Pass"),uncovered=environments.filter(item=>!item.dlp).length,managed=environments.filter(item=>item.managed).length,orphaned=environments.reduce((sum,item)=>sum+item.orphaned,0);$('#overallScore').textContent=snap.score;$('#overallRing').style.setProperty('--score',snap.score);$('#scoreTier').textContent=snap.score>=75?'Good':snap.score>=60?'Needs attention':'At risk';$('#scoreTrend').textContent=`+${snap.score-snap.previous} points since previous snapshot`;$('#criticalMetric').textContent=open.filter(item=>item.severity==='Critical').length;$('#environmentMetric').textContent=environments.length;$('#managedMetric').textContent=`${managed} managed`;$('#dlpMetric').textContent=`${Math.round((environments.length-uncovered)/environments.length*100)}%`;$('#dlpGapMetric').textContent=`${uncovered} uncovered`;$('#orphanMetric').textContent=orphaned;$('#navFindingCount').textContent=open.length;
$('#areaScores').innerHTML=areaScores.map(area=>{const score=area[activeSnapshot],tone=score<50?'danger':score<70?'warning':'';return `<div class="area-row"><span>${area.name}</span><div class="score-track"><div class="score-fill ${tone}" style="width:${score}%"></div></div><strong>${score}</strong></div>`}).join('');
$('#priorityActions').innerHTML=open.sort((a,b)=>severityRank(b.severity)-severityRank(a.severity)).slice(0,4).map((item,index)=>`<article class="priority-item" data-id="${item.id}" tabindex="0"><span class="priority-rank">0${index+1}</span><div><h3>${item.title}</h3><p>${item.scope} · ${item.effort} effort</p></div><span class="severity ${item.severity}">${item.severity}</span></article>`).join('');$$('.priority-item').forEach(item=>activate(item,()=>{selectedFinding=item.dataset.id;openView('findings')}));
$('#riskMap').innerHTML=environments.map(item=>`<button class="risk-tile ${item.risk}" data-id="${item.id}" type="button"><strong>${item.name}</strong><span>${item.findings.length} finding${item.findings.length===1?'':'s'}</span></button>`).join('');$$('.risk-tile').forEach(item=>item.addEventListener('click',()=>{selectedEnvironment=item.dataset.id;openView('environments')}));}
function renderEnvironments(){const search=$('#environmentSearch').value.toLowerCase(),risk=$('#riskFilter').value,managed=$('#managedFilter').value;const visible=environments.filter(item=>`${item.name} ${item.type} ${item.region}`.toLowerCase().includes(search)&&(risk==='all'||item.risk===risk)&&(managed==='all'||(managed==='managed'?item.managed:!item.managed)));if(!visible.some(item=>item.id===selectedEnvironment)&&visible.length)selectedEnvironment=visible[0].id;$('#environmentRows').innerHTML=visible.map(item=>`<tr data-id="${item.id}" class="${item.id===selectedEnvironment?'selected':''}" tabindex="0"><td><strong class="table-title">${item.name}</strong><span class="table-subtitle">${item.region}</span></td><td>${item.type}</td><td><span class="status-tag ${item.managed?'yes':'no'}">${item.managed?'Managed':'Standard'}</span></td><td><span class="status-tag ${item.dlp?'yes':'no'}">${item.dlp?'Covered':'Uncovered'}</span></td><td>${item.apps} apps · ${item.flows} flows</td><td><span class="risk-label ${item.risk}">${item.risk==='medium'?'Review':item.risk}</span></td></tr>`).join('');$('#environmentEmpty').hidden=visible.length>0;$$('#environmentRows tr').forEach(row=>activate(row,()=>{selectedEnvironment=row.dataset.id;renderEnvironments()}));renderEnvironmentDetail(environments.find(item=>item.id===selectedEnvironment));}
function renderEnvironmentDetail(item){const panel=$('#environmentDetail');if(!item){panel.className='detail-panel empty';panel.textContent='Select an environment to inspect its controls.';return}panel.className='detail-panel';const related=findings.filter(finding=>item.findings.includes(finding.id)),recommendation=item.risk==='high'?'Address DLP coverage and broad access before allowing additional production workloads.':item.risk==='medium'?'Enable managed controls and resolve outstanding ownership gaps.':'No urgent action. Continue monitoring this environment for drift.';panel.innerHTML=`<p class="eyebrow">${item.type} · ${item.region}</p><h2>${item.name}</h2><p>${item.managed?'Managed environment controls are active.':'Standard environment without managed governance controls.'}</p><div class="detail-grid"><div class="detail-metric"><span>Applications</span><strong>${item.apps}</strong></div><div class="detail-metric"><span>Flows</span><strong>${item.flows}</strong></div><div class="detail-metric"><span>Orphaned</span><strong>${item.orphaned}</strong></div><div class="detail-metric"><span>DLP policy</span><strong>${item.dlp?'Covered':'Missing'}</strong></div></div><div class="detail-section"><h3>Access boundary</h3><p>${item.securityGroup}</p></div><div class="detail-section"><h3>Open findings</h3>${related.length?`<ul>${related.map(f=>`<li>${f.id}: ${f.title}</li>`).join('')}</ul>`:'<p>No open findings for this environment.</p>'}</div><div class="detail-section"><h3>Next best action</h3><div class="recommendation-box">${recommendation}</div></div>`;}
function renderFindings(){const search=$('#findingSearch').value.toLowerCase(),severity=$('#severityFilter').value,area=$('#areaFilter').value,status=$('#statusFilter').value;const visible=snapshotFindings().filter(item=>`${item.id} ${item.title} ${item.evidence} ${item.scope}`.toLowerCase().includes(search)&&(severity==='all'||item.severity===severity)&&(area==='all'||item.area===area)&&(status==='all'||item.status===status)).sort((a,b)=>severityRank(b.severity)-severityRank(a.severity));if(!visible.some(item=>item.id===selectedFinding)&&visible.length)selectedFinding=visible[0].id;$('#findingList').innerHTML=visible.length?visible.map(item=>`<article class="finding-card ${item.id===selectedFinding?'selected':''}" data-id="${item.id}" tabindex="0"><i class="finding-status ${item.status}"></i><div><span class="rule-id">${item.id} · ${item.area}</span><h3>${item.title}</h3><p>${item.scope} · ${item.status}</p></div><span class="severity ${item.severity}">${item.severity}</span></article>`).join(''):'<div class="empty-state">No findings match these filters.</div>';$$('.finding-card').forEach(card=>activate(card,()=>{selectedFinding=card.dataset.id;renderFindings()}));renderFindingDetail(findings.find(item=>item.id===selectedFinding&&item[activeSnapshot]));}
function renderFindingDetail(item){const panel=$('#findingDetail');if(!item){panel.className='detail-panel empty';panel.textContent='Select a finding to review evidence and the next action.';return}panel.className='detail-panel';panel.innerHTML=`<div><span class="severity ${item.severity}">${item.severity}</span> <span class="rule-id">${item.id}</span></div><h2>${item.title}</h2><p>${item.area} · ${item.scope} · ${item.status}</p><div class="detail-section"><h3>Observed evidence</h3><p>${item.evidence}</p></div><div class="detail-section"><h3>Why it matters</h3><p>${item.impact}</p></div><div class="detail-section"><h3>Recommended action</h3><div class="recommendation-box">${item.recommendation}</div></div><div class="detail-grid"><div class="detail-metric"><span>Effort</span><strong>${item.effort}</strong></div><div class="detail-metric"><span>Remediation</span><strong>${item.status==='Pass'?'Monitor':'Script or manual'}</strong></div></div><button class="secondary-button" id="focusScope" type="button">Review affected scope</button>`;$('#focusScope').addEventListener('click',()=>{const env=environments.find(env=>env.findings.includes(item.id));if(env)selectedEnvironment=env.id;openView('environments')});}
function showCoverage(){$('#coverageContent').innerHTML=`<p class="dialog-intro">Coverage is shown with every score so missing permissions cannot create a misleading result.</p><div class="coverage-table"><div class="coverage-row header"><span>Collector</span><span>Coverage</span><span>Evidence</span></div>${coverage.map(row=>`<div class="coverage-row"><strong>${row[0]}</strong><span class="status-tag ${row[1]==='Full'?'yes':'no'}">${row[1]}</span><span>${row[2]}</span></div>`).join('')}</div>`;$('#coverageDialog').showModal()}
function showComparison(){$('#compareContent').innerHTML=`<div class="compare-summary"><div class="compare-snapshot"><p class="eyebrow">30 Jun 2026</p><strong>61</strong><span>Governance score · 44/48 rules evaluated</span></div><div class="compare-snapshot"><p class="eyebrow">14 Jul 2026</p><strong>68 <small>+7</small></strong><span>Governance score · 47/48 rules evaluated</span></div></div><div class="change-list"><div class="change-item"><b>Improved</b><p>DLP coverage increased from 50% to 75% after the baseline policy was extended.</p></div><div class="change-item"><b>Improved</b><p>Three orphaned flows received active owners.</p></div><div class="change-item"><b>New risk</b><p>Innovation Trial exceeded the 30-day policy.</p></div><div class="change-item"><b>Unchanged</b><p>Outbound tenant isolation remains disabled.</p></div></div>`;$('#compareDialog').showModal()}
function openCollection(){const names=['Tenant settings','Environments','DLP policies','Tenant isolation','Apps and flows','Directory owners'];$('#collectorList').innerHTML=names.map(name=>`<div class="collector-item"><strong>${name}</strong><span class="collector-state">Ready</span></div>`).join('');$('#startCollectionButton').disabled=false;$('#startCollectionButton').textContent='Start collection';$('#collectionDialog').showModal()}
function simulateCollection(){const states=[...$$('.collector-state')],button=$('#startCollectionButton');button.disabled=true;button.textContent='Collecting...';states.forEach((state,index)=>{state.textContent='Queued';setTimeout(()=>state.textContent='Collecting',index*180);setTimeout(()=>{state.textContent='Complete';state.classList.add('done');if(index===states.length-1){button.textContent='Snapshot complete';$('.connection-status').innerHTML='<i></i>Snapshot refreshed just now'}},index*180+420)})}
$$('.nav-item').forEach(item=>item.addEventListener('click',()=>openView(item.dataset.view)));$$('[data-open-view]').forEach(item=>item.addEventListener('click',()=>openView(item.dataset.openView)));$('#snapshotSelect').addEventListener('change',event=>{activeSnapshot=event.target.value;renderOverview();renderFindings()});['environmentSearch','riskFilter','managedFilter'].forEach(id=>$(`#${id}`).addEventListener('input',renderEnvironments));['findingSearch','severityFilter','areaFilter','statusFilter'].forEach(id=>$(`#${id}`).addEventListener('input',renderFindings));$('#coverageButton').addEventListener('click',showCoverage);$('#compareButton').addEventListener('click',showComparison);$('#collectButton').addEventListener('click',openCollection);$('#startCollectionButton').addEventListener('click',simulateCollection);$$('[data-close]').forEach(button=>button.addEventListener('click',()=>document.querySelector(`#${button.dataset.close}`).close()));
$('#areaFilter').innerHTML='<option value="all">All areas</option>'+[...new Set(findings.map(item=>item.area))].sort().map(area=>`<option value="${area}">${area}</option>`).join('');

const remediationEffects={
	dlp:{points:9,rules:["PPG-DLP-002"],areas:{"DLP policies":24},label:"DLP coverage reaches 100%"},
	sharing:{points:8,rules:["PPG-SHR-001","PPG-SHR-002"],areas:{"Sharing & ownership":22},label:"Broad sharing and ownership gaps resolved"},
	isolation:{points:8,rules:["PPG-ISO-001"],areas:{"Tenant isolation":39},label:"Outbound tenant isolation enabled"},
	managed:{points:5,rules:["PPG-ENV-002"],areas:{"Managed environments":16},label:"Production estate fully managed"}
};
const dlpPolicies=[
	{id:"baseline",name:"Zava Tenant Baseline",scope:"Tenant",environments:["prod-sales","prod-ops","dev-core","test-core","hr","coe"],connectors:{business:["Microsoft 365 Users","SharePoint","Dataverse","Teams"],nonbusiness:["Dropbox","Twitter","RSS"],blocked:["HTTP with Entra ID","FTP","Consumer Gmail"]}},
	{id:"default-strict",name:"Default Environment Guardrail",scope:"Northstar Default",environments:["default"],connectors:{business:["Microsoft 365 Users","SharePoint"],nonbusiness:["Teams"],blocked:["HTTP","SQL Server","Dropbox","Consumer Gmail"]}},
	{id:"innovation",name:"Innovation Restricted",scope:"Selected environments",environments:[],connectors:{business:["Microsoft 365 Users"],nonbusiness:["SharePoint","Teams"],blocked:["HTTP","Custom APIs","FTP","Dropbox"]}}
];
const customConnectors=new Set(["Custom APIs"]);
let queueMode="impact",selectedPolicy="baseline";
const comparedEnvironments=new Set();

function selectedRemediations(){return [...$$('#scenarioControls input:checked')].map(input=>input.value)}
function projectedScore(){return Math.min(96,snapshots[activeSnapshot].score+selectedRemediations().reduce((sum,key)=>sum+remediationEffects[key].points,0))}
function projectedRuleIds(){return new Set(selectedRemediations().flatMap(key=>remediationEffects[key].rules))}
function effectiveAreaScore(area){return Math.min(100,area[activeSnapshot]+selectedRemediations().reduce((sum,key)=>sum+(remediationEffects[key].areas[area.name]||0),0))}

function openView(name){$$('.view').forEach(view=>view.classList.toggle('active',view.id===`${name}View`));$$('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===name));$('#viewTitle').textContent=viewCopy[name][0];$('#viewDescription').textContent=viewCopy[name][1];if(name==='environments')renderEnvironments();if(name==='findings')renderFindings();if(name==='dlp')renderDlpMap()}

viewCopy.dlp=["DLP policy map","Trace policy coverage and connector classification across the Power Platform estate."];

function renderOverview(){
	const snap=snapshots[activeSnapshot],resolved=projectedRuleIds(),open=snapshotFindings().filter(item=>item.status!=="Pass"),effectiveOpen=open.filter(item=>!resolved.has(item.id));
	const uncovered=selectedRemediations().includes('dlp')?0:environments.filter(item=>!item.dlp).length;
	const managed=environments.filter(item=>item.managed).length+(selectedRemediations().includes('managed')?1:0);
	const orphaned=selectedRemediations().includes('sharing')?0:environments.reduce((sum,item)=>sum+item.orphaned,0);
	const score=projectedScore();
	$('#overallScore').textContent=score;$('#overallRing').style.setProperty('--score',score);$('#scoreTier').textContent=score>=90?'Excellent':score>=75?'Good':score>=60?'Needs attention':'At risk';
	$('#scoreTrend').textContent=selectedRemediations().length?`Projected +${score-snap.score} points from ${selectedRemediations().length} action${selectedRemediations().length===1?'':'s'}`:`+${snap.score-snap.previous} points since previous snapshot`;
	$('#criticalMetric').textContent=effectiveOpen.filter(item=>item.severity==='Critical').length;$('#environmentMetric').textContent=environments.length;$('#managedMetric').textContent=`${managed} managed`;$('#dlpMetric').textContent=`${Math.round((environments.length-uncovered)/environments.length*100)}%`;$('#dlpGapMetric').textContent=`${uncovered} uncovered`;$('#orphanMetric').textContent=orphaned;$('#navFindingCount').textContent=effectiveOpen.length;
	$('#scenarioSummary').textContent=selectedRemediations().length?selectedRemediations().map(key=>remediationEffects[key].label).join(' · '):'Current posture with no proposed actions applied.';
	$('#areaScores').innerHTML=areaScores.map(area=>{const value=effectiveAreaScore(area),tone=value<50?'danger':value<70?'warning':'';return `<div class="area-row"><span>${area.name}</span><div class="score-track"><div class="score-fill ${tone}" style="width:${value}%"></div></div><strong>${value}</strong></div>`}).join('');
	const ordered=[...open].sort((a,b)=>queueMode==='quick'?(effortRank(a.effort)-effortRank(b.effort))||(severityRank(b.severity)-severityRank(a.severity)):severityRank(b.severity)-severityRank(a.severity));
	$('#priorityActions').innerHTML=ordered.slice(0,4).map((item,index)=>`<article class="priority-item ${resolved.has(item.id)?'projected':''}" data-id="${item.id}" tabindex="0"><span class="priority-rank">0${index+1}</span><div><h3>${item.title}</h3><p>${item.scope} · ${item.effort} effort</p>${resolved.has(item.id)?'<span class="projected-label">Resolved in scenario</span>':''}</div><span class="severity ${item.severity}">${item.severity}</span></article>`).join('');
	$$('.priority-item').forEach(item=>activate(item,()=>{selectedFinding=item.dataset.id;openView('findings')}));
	$('#riskMap').innerHTML=environments.map(item=>{let risk=item.risk;if(selectedRemediations().includes('dlp')&&!item.dlp)risk='medium';if(selectedRemediations().includes('managed')&&item.id==='prod-ops')risk='low';if(selectedRemediations().includes('sharing')&&item.id==='default')risk='medium';return `<button class="risk-tile ${risk}" data-id="${item.id}" type="button"><strong>${item.name}</strong><span>${item.findings.filter(id=>!resolved.has(id)).length} open findings</span></button>`}).join('');
	$$('.risk-tile').forEach(item=>item.addEventListener('click',()=>{selectedEnvironment=item.dataset.id;openView('environments')}));
}

function effortRank(effort){return {None:0,Low:1,Medium:2,High:3}[effort]||4}

function renderEnvironments(){
	const search=$('#environmentSearch').value.toLowerCase(),risk=$('#riskFilter').value,managed=$('#managedFilter').value;
	const visible=environments.filter(item=>`${item.name} ${item.type} ${item.region}`.toLowerCase().includes(search)&&(risk==='all'||item.risk===risk)&&(managed==='all'||(managed==='managed'?item.managed:!item.managed)));
	if(!visible.some(item=>item.id===selectedEnvironment)&&visible.length)selectedEnvironment=visible[0].id;
	$('#environmentRows').innerHTML=visible.map(item=>`<tr data-id="${item.id}" class="${item.id===selectedEnvironment?'selected':''}" tabindex="0"><td><div class="environment-name-cell"><input class="environment-check" type="checkbox" data-compare-id="${item.id}" aria-label="Compare ${item.name}" ${comparedEnvironments.has(item.id)?'checked':''}><span><strong class="table-title">${item.name}</strong><span class="table-subtitle">${item.region}</span></span></div></td><td>${item.type}</td><td><span class="status-tag ${item.managed?'yes':'no'}">${item.managed?'Managed':'Standard'}</span></td><td><span class="status-tag ${item.dlp?'yes':'no'}">${item.dlp?'Covered':'Uncovered'}</span></td><td>${item.apps} apps · ${item.flows} flows</td><td><span class="risk-label ${item.risk}">${item.risk==='medium'?'Review':item.risk}</span></td></tr>`).join('');
	$('#environmentEmpty').hidden=visible.length>0;
	$$('#environmentRows tr').forEach(row=>activate(row,()=>{selectedEnvironment=row.dataset.id;renderEnvironments()}));
	$$('.environment-check').forEach(check=>check.addEventListener('click',event=>{event.stopPropagation();if(check.checked){if(comparedEnvironments.size>=3){check.checked=false;return}comparedEnvironments.add(check.dataset.compareId)}else comparedEnvironments.delete(check.dataset.compareId);updateEnvironmentCompareButton()}));
	updateEnvironmentCompareButton();renderEnvironmentDetail(environments.find(item=>item.id===selectedEnvironment));
}

function updateEnvironmentCompareButton(){const count=comparedEnvironments.size;$('#environmentCompareCount').textContent=count;$('#compareEnvironmentsButton').disabled=count<2}
function showEnvironmentComparison(){const items=environments.filter(item=>comparedEnvironments.has(item.id));$('#environmentCompareContent').innerHTML=`<div class="comparison-columns">${items.map(item=>`<section class="environment-column"><p class="eyebrow">${item.type} · ${item.region}</p><h3>${item.name}</h3><p>${item.securityGroup==='None'?'No security group boundary':item.securityGroup}</p><div class="comparison-metric"><span>Risk</span><strong class="risk-label ${item.risk}">${item.risk}</strong></div><div class="comparison-metric"><span>Managed</span><strong>${item.managed?'Yes':'No'}</strong></div><div class="comparison-metric"><span>DLP coverage</span><strong>${item.dlp?'Covered':'Missing'}</strong></div><div class="comparison-metric"><span>Apps / flows</span><strong>${item.apps} / ${item.flows}</strong></div><div class="comparison-metric"><span>Orphaned</span><strong>${item.orphaned}</strong></div><div class="comparison-verdict">${item.risk==='high'?'Prioritize controls before further adoption.':item.risk==='medium'?'Close governance gaps in the next review cycle.':'Suitable reference environment for governance patterns.'}</div></section>`).join('')}</div>`;$('#environmentCompareDialog').showModal()}

function renderFindings(){
	const search=$('#findingSearch').value.toLowerCase(),severity=$('#severityFilter').value,area=$('#areaFilter').value,status=$('#statusFilter').value;
	const visible=snapshotFindings().filter(item=>`${item.id} ${item.title} ${item.evidence} ${item.scope}`.toLowerCase().includes(search)&&(severity==='all'||item.severity===severity)&&(area==='all'||item.area===area)&&(status==='all'||item.status===status)).sort((a,b)=>severityRank(b.severity)-severityRank(a.severity));
	if(!visible.some(item=>item.id===selectedFinding)&&visible.length)selectedFinding=visible[0].id;
	const failed=visible.filter(item=>item.status==='Fail').length,critical=visible.filter(item=>item.severity==='Critical'&&item.status!=='Pass').length,quick=visible.filter(item=>item.effort==='Low'&&item.status!=='Pass').length;
	$('#executiveStrip').innerHTML=`<div class="executive-item"><strong>${visible.length}</strong><span>Matching controls</span></div><div class="executive-item"><strong>${failed}</strong><span>Failed</span></div><div class="executive-item"><strong>${critical}</strong><span>Critical</span></div><div class="executive-item"><strong>${quick}</strong><span>Low-effort actions</span></div>`;
	$('#findingList').innerHTML=visible.length?visible.map(item=>`<article class="finding-card ${item.id===selectedFinding?'selected':''}" data-id="${item.id}" tabindex="0"><i class="finding-status ${item.status}"></i><div><span class="rule-id">${item.id} · ${item.area}</span><h3>${item.title}</h3><p>${item.scope} · ${item.status}</p></div><span class="severity ${item.severity}">${item.severity}</span></article>`).join(''):'<div class="empty-state">No findings match these filters.</div>';
	$$('.finding-card').forEach(card=>activate(card,()=>{selectedFinding=card.dataset.id;renderFindings()}));renderFindingDetail(findings.find(item=>item.id===selectedFinding&&item[activeSnapshot]));
}

function renderDlpMap(){
	const selected=dlpPolicies.find(policy=>policy.id===selectedPolicy)||dlpPolicies[0],covered=new Set(dlpPolicies.flatMap(policy=>policy.environments));
	$('#dlpSummary').innerHTML=`<div class="metric"><strong>${dlpPolicies.length}</strong><span>Active policies</span><small>Tenant and scoped</small></div><div class="metric"><strong>${covered.size}/${environments.length}</strong><span>Environments covered</span><small>${environments.length-covered.size} need action</small></div><div class="metric"><strong>3</strong><span>Blocked connector types</span><small>Baseline policy</small></div><div class="metric"><strong>1</strong><span>Custom connectors</span><small>Classification review</small></div>`;
	$('#policyList').innerHTML=dlpPolicies.map(policy=>`<button class="policy-card ${policy.id===selectedPolicy?'active':''}" data-policy-id="${policy.id}" type="button"><strong>${policy.name}</strong><span>${policy.scope} · ${policy.environments.length} environments</span><span class="policy-coverage">${environments.map(env=>`<i class="${policy.environments.includes(env.id)?'covered':''}" title="${env.name}"></i>`).join('')}</span></button>`).join('');
	$$('.policy-card').forEach(card=>card.addEventListener('click',()=>{selectedPolicy=card.dataset.policyId;$('#connectorPolicyFilter').value=selectedPolicy;renderDlpMap()}));
	$('#connectorPolicyFilter').innerHTML=dlpPolicies.map(policy=>`<option value="${policy.id}" ${policy.id===selectedPolicy?'selected':''}>${policy.name}</option>`).join('');
	const labels={business:'Business',nonbusiness:'Non-business',blocked:'Blocked'};
	$('#connectorMap').innerHTML=Object.entries(selected.connectors).map(([group,connectors])=>`<section class="connector-group ${group}"><h3>${labels[group]}</h3><span>${connectors.length} connector${connectors.length===1?'':'s'}</span><div class="connector-list">${connectors.map(name=>`<div class="connector-item ${customConnectors.has(name)?'custom':''}">${name}</div>`).join('')}</div></section>`).join('');
}

$$('#scenarioControls input').forEach(input=>input.addEventListener('change',renderOverview));
$('#resetScenarioButton').addEventListener('click',()=>{$$('#scenarioControls input').forEach(input=>input.checked=false);renderOverview()});
$$('[data-queue-mode]').forEach(button=>button.addEventListener('click',()=>{queueMode=button.dataset.queueMode;$$('[data-queue-mode]').forEach(item=>item.classList.toggle('active',item===button));renderOverview()}));
$('#compareEnvironmentsButton').addEventListener('click',showEnvironmentComparison);
$('#connectorPolicyFilter').addEventListener('change',event=>{selectedPolicy=event.target.value;renderDlpMap()});
renderOverview();renderEnvironments();renderFindings();renderDlpMap();
